spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "12345"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update